classname=org.gwiz.wurmunlimited.mods.GwizServerTweaks
classpath=gwizservertweaks.jar
sharedClassLoader=true

allowInterfaithLink=true
spiritGuardsTargetUniques=true
towerGuardsTargetUniques=true
addDepositCoinAction=true
addInspectAnimalAction=true
addCoinsWhileDigging=true

# groomActionsPerAnimal (default: 10) - number of groom actions per animal, 0 = disabled                                    
groomActionsPerAnimal=10